from .calificar import GrupoCalificarSimulacroView, RevisarSimulacroView
from .resultados import ResultadosSimulacroListView
from .pdf import DescargarResultadosPDFView, DescargarInformeDirectivoPDFView, DescargarResultadosRealesPDFView, DescargarResultadoIndividualPDFView
