# Generated by Django 5.1.3 on 2025-02-05 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='municipio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios', to='ubicaciones.municipio'),
        ),
    ]
