# Generated by Django 5.1.15 on 2026-04-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubicaciones", "0001_initial"),
        ("usuarios", "0007_usuario_departamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="ubicaciones.sede",
            ),
        ),
    ]
